opt:
  lr: 0.0001
  wd: 0.0005
  b1: 0.5
  b2: 0.999
  n_critic: 5
  dataset: cifar10
  data_path: ~/awesomePhD/Datasets/
  batch_size: 4
  seed: 2020
  num_workers: 4
  latent_dim: 100
  lambda_gp: 10

  net_E: vanilla
  net_E_params:
    latent_dim: 100
    feat: 128
    img_nc: 3

  net_G: vanilla
  net_G_params:
    latent_dim: 100
    feat: 128
    img_nc: 3

  net_D: vanilla
  net_D_params:
    latent_dim: 100
    feat: 128
    img_nc: 3
    neg_slope: 0.2


trainer_opt:
  gpus: 0
  max_steps: 100
  precision: 32
  min_epochs: 1
  log_save_interval: 100
  num_sanity_val_steps: 1
  early_stop_callback: False
  limit_train_batches: 0.001
  limit_val_batches: 1.0
  deterministic: True 
#  distributed_backend: ddp

logging_opt:
  save_dir: ./logs/
  name: cifar10
  version: cifar10_w

ckpt_opt:
  save_top_k: -1
  period: 10